/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define MiniXftConfigconst const
#else
#define MiniXftConfigconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN MiniXftConfig_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((MiniXftConfig_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE MiniXftConfigrestart( MiniXftConfigin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct MiniXftConfig_buffer_state *YY_BUFFER_STATE;

extern int MiniXftConfigleng;
extern FILE *MiniXftConfigin, *MiniXftConfigout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		MiniXftConfigless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the MiniXftConfigless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define MiniXftConfigless(n) \
	do \
		{ \
		/* Undo effects of setting up MiniXftConfigtext. */ \
		*MiniXftConfig_cp = MiniXftConfig_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		MiniXftConfig_c_buf_p = MiniXftConfig_cp = MiniXftConfig_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up MiniXftConfigtext again */ \
		} \
	while ( 0 )

#define unput(c) MiniXftConfigunput( c, MiniXftConfigtext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int MiniXftConfig_size_t;


struct MiniXftConfig_buffer_state
	{
	FILE *MiniXftConfig_input_file;

	char *MiniXftConfig_ch_buf;		/* input buffer */
	char *MiniXftConfig_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	MiniXftConfig_size_t MiniXftConfig_buf_size;

	/* Number of characters read into MiniXftConfig_ch_buf, not including EOB
	 * characters.
	 */
	int MiniXftConfig_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int MiniXftConfig_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int MiniXftConfig_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int MiniXftConfig_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int MiniXftConfig_fill_buffer;

	int MiniXftConfig_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via MiniXftConfigrestart()), so that the user can continue scanning by
	 * just pointing MiniXftConfigin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE MiniXftConfig_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER MiniXftConfig_current_buffer


/* MiniXftConfig_hold_char holds the character lost when MiniXftConfigtext is formed. */
static char MiniXftConfig_hold_char;

static int MiniXftConfig_n_chars;		/* number of characters read into MiniXftConfig_ch_buf */


int MiniXftConfigleng;

/* Points to current character in buffer. */
static char *MiniXftConfig_c_buf_p = (char *) 0;
static int MiniXftConfig_init = 1;		/* whether we need to initialize */
static int MiniXftConfig_start = 0;	/* start state number */

/* Flag which is used to allow MiniXftConfigwrap()'s to do buffer switches
 * instead of setting up a fresh MiniXftConfigin.  A bit of a hack ...
 */
static int MiniXftConfig_did_buffer_switch_on_eof;

void MiniXftConfigrestart YY_PROTO(( FILE *input_file ));

void MiniXftConfig_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void MiniXftConfig_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE MiniXftConfig_create_buffer YY_PROTO(( FILE *file, int size ));
void MiniXftConfig_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void MiniXftConfig_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void MiniXftConfig_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER MiniXftConfig_flush_buffer( MiniXftConfig_current_buffer )

YY_BUFFER_STATE MiniXftConfig_scan_buffer YY_PROTO(( char *base, MiniXftConfig_size_t size ));
YY_BUFFER_STATE MiniXftConfig_scan_string YY_PROTO(( MiniXftConfigconst char *MiniXftConfig_str ));
YY_BUFFER_STATE MiniXftConfig_scan_bytes YY_PROTO(( MiniXftConfigconst char *bytes, int len ));

static void *MiniXftConfig_flex_alloc YY_PROTO(( MiniXftConfig_size_t ));
static void *MiniXftConfig_flex_realloc YY_PROTO(( void *, MiniXftConfig_size_t ));
static void MiniXftConfig_flex_free YY_PROTO(( void * ));

#define MiniXftConfig_new_buffer MiniXftConfig_create_buffer

#define MiniXftConfig_set_interactive(is_interactive) \
	{ \
	if ( ! MiniXftConfig_current_buffer ) \
		MiniXftConfig_current_buffer = MiniXftConfig_create_buffer( MiniXftConfigin, YY_BUF_SIZE ); \
	MiniXftConfig_current_buffer->MiniXftConfig_is_interactive = is_interactive; \
	}

#define MiniXftConfig_set_bol(at_bol) \
	{ \
	if ( ! MiniXftConfig_current_buffer ) \
		MiniXftConfig_current_buffer = MiniXftConfig_create_buffer( MiniXftConfigin, YY_BUF_SIZE ); \
	MiniXftConfig_current_buffer->MiniXftConfig_at_bol = at_bol; \
	}

#define YY_AT_BOL() (MiniXftConfig_current_buffer->MiniXftConfig_at_bol)

typedef unsigned char YY_CHAR;
FILE *MiniXftConfigin = (FILE *) 0, *MiniXftConfigout = (FILE *) 0;
typedef int MiniXftConfig_state_type;
extern char *MiniXftConfigtext;
#define MiniXftConfigtext_ptr MiniXftConfigtext

static MiniXftConfig_state_type MiniXftConfig_get_previous_state YY_PROTO(( void ));
static MiniXftConfig_state_type MiniXftConfig_try_NUL_trans YY_PROTO(( MiniXftConfig_state_type current_state ));
static int MiniXftConfig_get_next_buffer YY_PROTO(( void ));
static void MiniXftConfig_fatal_error YY_PROTO(( MiniXftConfigconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up MiniXftConfigtext.
 */
#define YY_DO_BEFORE_ACTION \
	MiniXftConfigtext_ptr = MiniXftConfig_bp; \
	MiniXftConfigleng = (int) (MiniXftConfig_cp - MiniXftConfig_bp); \
	MiniXftConfig_hold_char = *MiniXftConfig_cp; \
	*MiniXftConfig_cp = '\0'; \
	MiniXftConfig_c_buf_p = MiniXftConfig_cp;

#define YY_NUM_RULES 39
#define YY_END_OF_BUFFER 40
static MiniXftConfigconst short int MiniXftConfig_accept[94] =
    {   0,
        0,    0,   40,   37,   38,   21,   37,   37,   19,   17,
       18,   37,   20,   34,   15,   16,   24,   14,   28,   30,
       36,   31,   32,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   37,    2,   29,    0,   33,    0,   22,   35,
        0,    1,   35,   34,    0,   25,   26,   27,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   23,
       33,    0,   35,    0,    0,   35,   13,   12,   36,    3,
       36,   36,   36,   36,   11,   36,   35,    0,   36,    8,
       36,   36,   36,    9,    4,   10,   36,    7,   36,    5,
       36,    6,    0

    } ;

static MiniXftConfigconst int MiniXftConfig_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    1,    6,    1,    1,
        1,    7,    8,    1,    9,   10,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,   15,
       16,   17,   18,    1,   19,   19,   19,   19,   20,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       21,   22,   23,    1,   24,    1,   25,   19,   26,   27,

       28,   29,   19,   30,   31,   19,   19,   32,   33,   34,
       19,   19,   19,   35,   36,   37,   38,   19,   19,   19,
       39,   19,   40,   41,   42,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static MiniXftConfigconst int MiniXftConfig_meta[43] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    1,    1,    1,    1,    3,    3,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1,    1
    } ;

static MiniXftConfigconst short int MiniXftConfig_base[96] =
    {   0,
        0,  126,  130,  132,  132,  113,   39,  122,  132,  132,
      132,   32,  120,   35,  132,  132,  110,  109,  108,  132,
        0,  132,  132,   14,   98,   91,   94,   95,   85,   93,
       86,   81,   74,  132,  132,   45,  132,   46,  132,   42,
      102,  132,   45,   46,   67,  132,  132,  132,    0,   81,
       73,   85,   75,   77,   73,   78,   66,   70,   63,  132,
       47,   41,   66,   88,   87,   86,    0,    0,   67,    0,
       59,   59,   61,   66,    0,   63,   32,   47,   62,    0,
       60,   49,   54,    0,    0,    0,   54,    0,   52,   46,
       42,    0,  132,  106,   61

    } ;

static MiniXftConfigconst short int MiniXftConfig_def[96] =
    {   0,
       93,    1,   93,   93,   93,   93,   94,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       95,   93,   93,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   93,   93,   93,   94,   93,   94,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   93,
       94,   93,   93,   93,   93,   93,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   93,   93,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,    0,   93,   93

    } ;

static MiniXftConfigconst short int MiniXftConfig_nxt[175] =
    {   0,
        4,    5,    6,    7,    4,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       22,    4,   23,    4,   24,   25,   26,   27,   28,   21,
       29,   21,   30,   31,   21,   21,   32,   21,   21,    4,
       33,    4,   37,   40,   43,   50,   44,   51,   37,   61,
       37,   45,   62,   40,   45,   43,   63,   44,   78,   45,
       38,   45,   45,   49,   45,   45,   38,   38,   38,   45,
       92,   41,   45,   45,   65,   65,   91,   63,   66,   90,
       89,   41,   77,   88,   64,   45,   87,   86,   77,   85,
       84,   83,   82,   45,   81,   80,   79,   66,   66,   78,

       76,   75,   74,   73,   72,   64,   36,   71,   36,   70,
       69,   68,   67,   62,   60,   59,   58,   57,   56,   55,
       54,   53,   52,   48,   47,   46,   42,   39,   35,   93,
       34,    3,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93
    } ;

static MiniXftConfigconst short int MiniXftConfig_chk[175] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    7,   12,   14,   24,   14,   24,   36,   38,
       61,   77,   62,   40,   14,   44,   43,   44,   78,   77,
        7,   40,   14,   95,   43,   44,   36,   38,   61,   40,
       91,   12,   43,   44,   45,   45,   90,   63,   45,   89,
       87,   40,   62,   83,   43,   63,   82,   81,   78,   79,
       76,   74,   73,   63,   72,   71,   69,   66,   65,   64,

       59,   58,   57,   56,   55,   63,   94,   54,   94,   53,
       52,   51,   50,   41,   33,   32,   31,   30,   29,   28,
       27,   26,   25,   19,   18,   17,   13,    8,    6,    3,
        2,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93
    } ;

static MiniXftConfig_state_type MiniXftConfig_last_accepting_state;
static char *MiniXftConfig_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define MiniXftConfigmore() MiniXftConfigmore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *MiniXftConfigtext;
#line 1 "minixftlex.l"
#define INITIAL 0
#line 2 "minixftlex.l"
/*
 * $XFree86: xc/lib/MiniXft/xftlex.l,v 1.7 2001/05/18 16:03:06 tsi Exp $
 *
 * Copyright (c) 2000 Keith Packard, member of The XFree86 Project, Inc.
 *
 * Permission to use, copy, modify, distribute, and sell this software and its
 * documentation for any purpose is hereby granted without fee, provided that
 * the above copyright notice appear in all copies and that both that
 * copyright notice and this permission notice appear in supporting
 * documentation, and that the name of Keith Packard not be used in
 * advertising or publicity pertaining to distribution of the software without
 * specific, written prior permission.  Keith Packard makes no
 * representations about the suitability of this software for any purpose.  It
 * is provided "as is" without express or implied warranty.
 *
 * KEITH PACKARD DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
 * INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
 * EVENT SHALL KEITH PACKARD BE LIABLE FOR ANY SPECIAL, INDIRECT OR
 * CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
 * DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 * TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THIS SOFTWARE.
 */

#include <string.h>
#include "minixftint.h"

#include "minixftgram.h"

int	    MiniXftConfigLineno;

static void _MiniXftConfigSkipComment (void);

static void _MiniXftConfigSkipLine (void);
    
static int _MiniXftConfigPopInput (void);
    
    
#define		XFT_CONFIG_IN_DEEP	20
FILE	*MiniXftConfigInStack[XFT_CONFIG_IN_DEEP];
FILE	**MiniXftConfigInpt = MiniXftConfigInStack + XFT_CONFIG_IN_DEEP;
FILE	*MiniXftConfigInput;
int	MiniXftConfigLinenos[XFT_CONFIG_IN_DEEP];
int 	*MiniXftConfigLinenopt = MiniXftConfigLinenos + XFT_CONFIG_IN_DEEP;
char	*MiniXftConfigFile = "";
char	*MiniXftConfigFileNames[XFT_CONFIG_IN_DEEP];
char	**MiniXftConfigFileNamePt = MiniXftConfigFileNames + XFT_CONFIG_IN_DEEP;
int	MiniXftConfigFiledeep = 0;

#undef YY_INPUT

#define YY_INPUT(buf,result,max_size) \
{ \
    int c; \
    result = 0; \
    while (result < max_size) { \
	c = getc (MiniXftConfigInput); \
	if (c < 0) { \
	    c = _MiniXftConfigPopInput (); \
	    if (c < 0) \
		break; \
	} \
	buf[result++] = c; \
	if (c == '\n') \
	{ \
	    MiniXftConfigLineno++; \
	    break; \
	} \
    } \
}
    
#ifndef FLEX_SCANNER
#undef		input
#undef		unput
static int input (void)
{
    char    buf[1];
    static  int	r = EOF;

    if (r == 0)
	return 0;
    YY_INPUT(buf, r, 1);
    if (r == 0)
	return EOF;
    return buf[0];
}

static void unput (char c)
{
    if (!c || c == EOF)
	return;
    if (c == '\n')
	MiniXftConfigLineno--;
    ungetc (c, MiniXftConfigInput);
}
#endif

#line 531 "lex.MiniXftConfig.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int MiniXftConfigwrap YY_PROTO(( void ));
#else
extern int MiniXftConfigwrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void MiniXftConfigunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef MiniXftConfigtext_ptr
static void MiniXftConfig_flex_strncpy YY_PROTO(( char *, MiniXftConfigconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int MiniXftConfig_flex_strlen YY_PROTO(( MiniXftConfigconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int MiniXftConfiginput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int MiniXftConfig_start_stack_ptr = 0;
static int MiniXftConfig_start_stack_depth = 0;
static int *MiniXftConfig_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void MiniXftConfig_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void MiniXftConfig_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int MiniXftConfig_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( MiniXftConfigtext, MiniXftConfigleng, 1, MiniXftConfigout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( MiniXftConfig_current_buffer->MiniXftConfig_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( MiniXftConfigin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( MiniXftConfigin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, MiniXftConfigin )) == 0) \
		  && ferror( MiniXftConfigin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "MiniXftConfigterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef MiniXftConfigterminate
#define MiniXftConfigterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) MiniXftConfig_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int MiniXftConfiglex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after MiniXftConfigtext and MiniXftConfigleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( MiniXftConfigleng > 0 ) \
		MiniXftConfig_current_buffer->MiniXftConfig_at_bol = \
				(MiniXftConfigtext[MiniXftConfigleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register MiniXftConfig_state_type MiniXftConfig_current_state;
	register char *MiniXftConfig_cp = NULL, *MiniXftConfig_bp = NULL;
	register int MiniXftConfig_act;

#line 100 "minixftlex.l"

#line 687 "lex.MiniXftConfig.c"

	if ( MiniXftConfig_init )
		{
		MiniXftConfig_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! MiniXftConfig_start )
			MiniXftConfig_start = 1;	/* first start state */

		if ( ! MiniXftConfigin )
			MiniXftConfigin = stdin;

		if ( ! MiniXftConfigout )
			MiniXftConfigout = stdout;

		if ( ! MiniXftConfig_current_buffer )
			MiniXftConfig_current_buffer =
				MiniXftConfig_create_buffer( MiniXftConfigin, YY_BUF_SIZE );

		MiniXftConfig_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		MiniXftConfig_cp = MiniXftConfig_c_buf_p;

		/* Support of MiniXftConfigtext. */
		*MiniXftConfig_cp = MiniXftConfig_hold_char;

		/* MiniXftConfig_bp points to the position in MiniXftConfig_ch_buf of the start of
		 * the current run.
		 */
		MiniXftConfig_bp = MiniXftConfig_cp;

		MiniXftConfig_current_state = MiniXftConfig_start;
		MiniXftConfig_current_state += YY_AT_BOL();
MiniXftConfig_match:
		do
			{
			register YY_CHAR MiniXftConfig_c = MiniXftConfig_ec[YY_SC_TO_UI(*MiniXftConfig_cp)];
			if ( MiniXftConfig_accept[MiniXftConfig_current_state] )
				{
				MiniXftConfig_last_accepting_state = MiniXftConfig_current_state;
				MiniXftConfig_last_accepting_cpos = MiniXftConfig_cp;
				}
			while ( MiniXftConfig_chk[MiniXftConfig_base[MiniXftConfig_current_state] + MiniXftConfig_c] != MiniXftConfig_current_state )
				{
				MiniXftConfig_current_state = (int) MiniXftConfig_def[MiniXftConfig_current_state];
				if ( MiniXftConfig_current_state >= 94 )
					MiniXftConfig_c = MiniXftConfig_meta[(unsigned int) MiniXftConfig_c];
				}
			MiniXftConfig_current_state = MiniXftConfig_nxt[MiniXftConfig_base[MiniXftConfig_current_state] + (unsigned int) MiniXftConfig_c];
			++MiniXftConfig_cp;
			}
		while ( MiniXftConfig_base[MiniXftConfig_current_state] != 132 );

MiniXftConfig_find_action:
		MiniXftConfig_act = MiniXftConfig_accept[MiniXftConfig_current_state];
		if ( MiniXftConfig_act == 0 )
			{ /* have to back up */
			MiniXftConfig_cp = MiniXftConfig_last_accepting_cpos;
			MiniXftConfig_current_state = MiniXftConfig_last_accepting_state;
			MiniXftConfig_act = MiniXftConfig_accept[MiniXftConfig_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( MiniXftConfig_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*MiniXftConfig_cp = MiniXftConfig_hold_char;
			MiniXftConfig_cp = MiniXftConfig_last_accepting_cpos;
			MiniXftConfig_current_state = MiniXftConfig_last_accepting_state;
			goto MiniXftConfig_find_action;

case 1:
YY_RULE_SETUP
#line 101 "minixftlex.l"
_MiniXftConfigSkipComment();
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 102 "minixftlex.l"
_MiniXftConfigSkipLine();
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 103 "minixftlex.l"
return DIR;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 104 "minixftlex.l"
return CACHE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 105 "minixftlex.l"
return INCLUDE;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 106 "minixftlex.l"
return INCLUDEIF;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 107 "minixftlex.l"
return MATCH;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 108 "minixftlex.l"
return EDIT;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 109 "minixftlex.l"
return TOK_TRUE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 110 "minixftlex.l"
return TOK_FALSE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 111 "minixftlex.l"
return TOK_NIL;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 112 "minixftlex.l"
return ANY;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 113 "minixftlex.l"
return ALL;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 114 "minixftlex.l"
return EQUAL;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 115 "minixftlex.l"
return COLON;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 116 "minixftlex.l"
return SEMI;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 117 "minixftlex.l"
return PLUS;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 118 "minixftlex.l"
return MINUS;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 119 "minixftlex.l"
return TIMES;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 120 "minixftlex.l"
return DIVIDE;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 121 "minixftlex.l"
return NOT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 122 "minixftlex.l"
return ANDAND;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 123 "minixftlex.l"
return OROR;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 124 "minixftlex.l"
return LESS;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 125 "minixftlex.l"
return LESSEQ;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 126 "minixftlex.l"
return EQEQ;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 127 "minixftlex.l"
return MOREEQ;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 128 "minixftlex.l"
return MORE;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 129 "minixftlex.l"
return NOTEQ;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 130 "minixftlex.l"
return QUEST;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 131 "minixftlex.l"
return OS;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 132 "minixftlex.l"
return CS;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 133 "minixftlex.l"
{
    			MiniXftConfigtext[MiniXftConfigleng - 1] = '\0';
			MiniXftConfiglval.sval = MiniXftConfigtext+1;
			return STRING;
		}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 138 "minixftlex.l"
{
		MiniXftConfiglval.ival = strtol (MiniXftConfigtext, 0, 10);
		return INTEGER;
		}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 142 "minixftlex.l"
{
		MiniXftConfiglval.dval = strtod (MiniXftConfigtext, 0);
		return DOUBLE;
		}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 146 "minixftlex.l"
{
		if (MiniXftNameConstant (MiniXftConfigtext, &MiniXftConfiglval.ival))
		    return INTEGER;
		MiniXftConfiglval.sval = MiniXftConfigtext;
		return NAME;
		}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 152 "minixftlex.l"
;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 153 "minixftlex.l"
;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 154 "minixftlex.l"
ECHO;
	YY_BREAK
#line 981 "lex.MiniXftConfig.c"
case YY_STATE_EOF(INITIAL):
	MiniXftConfigterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int MiniXftConfig_amount_of_matched_text = (int) (MiniXftConfig_cp - MiniXftConfigtext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*MiniXftConfig_cp = MiniXftConfig_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( MiniXftConfig_current_buffer->MiniXftConfig_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed MiniXftConfigin at a new source and called
			 * MiniXftConfiglex().  If so, then we have to assure
			 * consistency between MiniXftConfig_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			MiniXftConfig_n_chars = MiniXftConfig_current_buffer->MiniXftConfig_n_chars;
			MiniXftConfig_current_buffer->MiniXftConfig_input_file = MiniXftConfigin;
			MiniXftConfig_current_buffer->MiniXftConfig_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for MiniXftConfig_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since MiniXftConfig_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( MiniXftConfig_c_buf_p <= &MiniXftConfig_current_buffer->MiniXftConfig_ch_buf[MiniXftConfig_n_chars] )
			{ /* This was really a NUL. */
			MiniXftConfig_state_type MiniXftConfig_next_state;

			MiniXftConfig_c_buf_p = MiniXftConfigtext_ptr + MiniXftConfig_amount_of_matched_text;

			MiniXftConfig_current_state = MiniXftConfig_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * MiniXftConfig_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			MiniXftConfig_next_state = MiniXftConfig_try_NUL_trans( MiniXftConfig_current_state );

			MiniXftConfig_bp = MiniXftConfigtext_ptr + YY_MORE_ADJ;

			if ( MiniXftConfig_next_state )
				{
				/* Consume the NUL. */
				MiniXftConfig_cp = ++MiniXftConfig_c_buf_p;
				MiniXftConfig_current_state = MiniXftConfig_next_state;
				goto MiniXftConfig_match;
				}

			else
				{
				MiniXftConfig_cp = MiniXftConfig_c_buf_p;
				goto MiniXftConfig_find_action;
				}
			}

		else switch ( MiniXftConfig_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				MiniXftConfig_did_buffer_switch_on_eof = 0;

				if ( MiniXftConfigwrap() )
					{
					/* Note: because we've taken care in
					 * MiniXftConfig_get_next_buffer() to have set up
					 * MiniXftConfigtext, we can now set up
					 * MiniXftConfig_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					MiniXftConfig_c_buf_p = MiniXftConfigtext_ptr + YY_MORE_ADJ;

					MiniXftConfig_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! MiniXftConfig_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				MiniXftConfig_c_buf_p =
					MiniXftConfigtext_ptr + MiniXftConfig_amount_of_matched_text;

				MiniXftConfig_current_state = MiniXftConfig_get_previous_state();

				MiniXftConfig_cp = MiniXftConfig_c_buf_p;
				MiniXftConfig_bp = MiniXftConfigtext_ptr + YY_MORE_ADJ;
				goto MiniXftConfig_match;

			case EOB_ACT_LAST_MATCH:
				MiniXftConfig_c_buf_p =
				&MiniXftConfig_current_buffer->MiniXftConfig_ch_buf[MiniXftConfig_n_chars];

				MiniXftConfig_current_state = MiniXftConfig_get_previous_state();

				MiniXftConfig_cp = MiniXftConfig_c_buf_p;
				MiniXftConfig_bp = MiniXftConfigtext_ptr + YY_MORE_ADJ;
				goto MiniXftConfig_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of MiniXftConfiglex */


/* MiniXftConfig_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int MiniXftConfig_get_next_buffer()
	{
	register char *dest = MiniXftConfig_current_buffer->MiniXftConfig_ch_buf;
	register char *source = MiniXftConfigtext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( MiniXftConfig_c_buf_p > &MiniXftConfig_current_buffer->MiniXftConfig_ch_buf[MiniXftConfig_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( MiniXftConfig_current_buffer->MiniXftConfig_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( MiniXftConfig_c_buf_p - MiniXftConfigtext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (MiniXftConfig_c_buf_p - MiniXftConfigtext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( MiniXftConfig_current_buffer->MiniXftConfig_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		MiniXftConfig_current_buffer->MiniXftConfig_n_chars = MiniXftConfig_n_chars = 0;

	else
		{
		int num_to_read =
			MiniXftConfig_current_buffer->MiniXftConfig_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = MiniXftConfig_current_buffer;

			int MiniXftConfig_c_buf_p_offset =
				(int) (MiniXftConfig_c_buf_p - b->MiniXftConfig_ch_buf);

			if ( b->MiniXftConfig_is_our_buffer )
				{
				int new_size = b->MiniXftConfig_buf_size * 2;

				if ( new_size <= 0 )
					b->MiniXftConfig_buf_size += b->MiniXftConfig_buf_size / 8;
				else
					b->MiniXftConfig_buf_size *= 2;

				b->MiniXftConfig_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					MiniXftConfig_flex_realloc( (void *) b->MiniXftConfig_ch_buf,
							 b->MiniXftConfig_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->MiniXftConfig_ch_buf = 0;

			if ( ! b->MiniXftConfig_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			MiniXftConfig_c_buf_p = &b->MiniXftConfig_ch_buf[MiniXftConfig_c_buf_p_offset];

			num_to_read = MiniXftConfig_current_buffer->MiniXftConfig_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&MiniXftConfig_current_buffer->MiniXftConfig_ch_buf[number_to_move]),
			MiniXftConfig_n_chars, num_to_read );

		MiniXftConfig_current_buffer->MiniXftConfig_n_chars = MiniXftConfig_n_chars;
		}

	if ( MiniXftConfig_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			MiniXftConfigrestart( MiniXftConfigin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			MiniXftConfig_current_buffer->MiniXftConfig_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	MiniXftConfig_n_chars += number_to_move;
	MiniXftConfig_current_buffer->MiniXftConfig_ch_buf[MiniXftConfig_n_chars] = YY_END_OF_BUFFER_CHAR;
	MiniXftConfig_current_buffer->MiniXftConfig_ch_buf[MiniXftConfig_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	MiniXftConfigtext_ptr = &MiniXftConfig_current_buffer->MiniXftConfig_ch_buf[0];

	return ret_val;
	}


/* MiniXftConfig_get_previous_state - get the state just before the EOB char was reached */

static MiniXftConfig_state_type MiniXftConfig_get_previous_state()
	{
	register MiniXftConfig_state_type MiniXftConfig_current_state;
	register char *MiniXftConfig_cp;

	MiniXftConfig_current_state = MiniXftConfig_start;
	MiniXftConfig_current_state += YY_AT_BOL();

	for ( MiniXftConfig_cp = MiniXftConfigtext_ptr + YY_MORE_ADJ; MiniXftConfig_cp < MiniXftConfig_c_buf_p; ++MiniXftConfig_cp )
		{
		register YY_CHAR MiniXftConfig_c = (*MiniXftConfig_cp ? MiniXftConfig_ec[YY_SC_TO_UI(*MiniXftConfig_cp)] : 1);
		if ( MiniXftConfig_accept[MiniXftConfig_current_state] )
			{
			MiniXftConfig_last_accepting_state = MiniXftConfig_current_state;
			MiniXftConfig_last_accepting_cpos = MiniXftConfig_cp;
			}
		while ( MiniXftConfig_chk[MiniXftConfig_base[MiniXftConfig_current_state] + MiniXftConfig_c] != MiniXftConfig_current_state )
			{
			MiniXftConfig_current_state = (int) MiniXftConfig_def[MiniXftConfig_current_state];
			if ( MiniXftConfig_current_state >= 94 )
				MiniXftConfig_c = MiniXftConfig_meta[(unsigned int) MiniXftConfig_c];
			}
		MiniXftConfig_current_state = MiniXftConfig_nxt[MiniXftConfig_base[MiniXftConfig_current_state] + (unsigned int) MiniXftConfig_c];
		}

	return MiniXftConfig_current_state;
	}


/* MiniXftConfig_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = MiniXftConfig_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static MiniXftConfig_state_type MiniXftConfig_try_NUL_trans( MiniXftConfig_state_type MiniXftConfig_current_state )
#else
static MiniXftConfig_state_type MiniXftConfig_try_NUL_trans( MiniXftConfig_current_state )
MiniXftConfig_state_type MiniXftConfig_current_state;
#endif
	{
	register int MiniXftConfig_is_jam;
	register char *MiniXftConfig_cp = MiniXftConfig_c_buf_p;

	register YY_CHAR MiniXftConfig_c = 1;
	if ( MiniXftConfig_accept[MiniXftConfig_current_state] )
		{
		MiniXftConfig_last_accepting_state = MiniXftConfig_current_state;
		MiniXftConfig_last_accepting_cpos = MiniXftConfig_cp;
		}
	while ( MiniXftConfig_chk[MiniXftConfig_base[MiniXftConfig_current_state] + MiniXftConfig_c] != MiniXftConfig_current_state )
		{
		MiniXftConfig_current_state = (int) MiniXftConfig_def[MiniXftConfig_current_state];
		if ( MiniXftConfig_current_state >= 94 )
			MiniXftConfig_c = MiniXftConfig_meta[(unsigned int) MiniXftConfig_c];
		}
	MiniXftConfig_current_state = MiniXftConfig_nxt[MiniXftConfig_base[MiniXftConfig_current_state] + (unsigned int) MiniXftConfig_c];
	MiniXftConfig_is_jam = (MiniXftConfig_current_state == 93);

	return MiniXftConfig_is_jam ? 0 : MiniXftConfig_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void MiniXftConfigunput( int c, register char *MiniXftConfig_bp )
#else
static void MiniXftConfigunput( c, MiniXftConfig_bp )
int c;
register char *MiniXftConfig_bp;
#endif
	{
	register char *MiniXftConfig_cp = MiniXftConfig_c_buf_p;

	/* undo effects of setting up MiniXftConfigtext */
	*MiniXftConfig_cp = MiniXftConfig_hold_char;

	if ( MiniXftConfig_cp < MiniXftConfig_current_buffer->MiniXftConfig_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = MiniXftConfig_n_chars + 2;
		register char *dest = &MiniXftConfig_current_buffer->MiniXftConfig_ch_buf[
					MiniXftConfig_current_buffer->MiniXftConfig_buf_size + 2];
		register char *source =
				&MiniXftConfig_current_buffer->MiniXftConfig_ch_buf[number_to_move];

		while ( source > MiniXftConfig_current_buffer->MiniXftConfig_ch_buf )
			*--dest = *--source;

		MiniXftConfig_cp += (int) (dest - source);
		MiniXftConfig_bp += (int) (dest - source);
		MiniXftConfig_current_buffer->MiniXftConfig_n_chars =
			MiniXftConfig_n_chars = MiniXftConfig_current_buffer->MiniXftConfig_buf_size;

		if ( MiniXftConfig_cp < MiniXftConfig_current_buffer->MiniXftConfig_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--MiniXftConfig_cp = (char) c;


	MiniXftConfigtext_ptr = MiniXftConfig_bp;
	MiniXftConfig_hold_char = *MiniXftConfig_cp;
	MiniXftConfig_c_buf_p = MiniXftConfig_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int MiniXftConfiginput()
#else
static int input()
#endif
	{
	int c;

	*MiniXftConfig_c_buf_p = MiniXftConfig_hold_char;

	if ( *MiniXftConfig_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* MiniXftConfig_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( MiniXftConfig_c_buf_p < &MiniXftConfig_current_buffer->MiniXftConfig_ch_buf[MiniXftConfig_n_chars] )
			/* This was really a NUL. */
			*MiniXftConfig_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = MiniXftConfig_c_buf_p - MiniXftConfigtext_ptr;
			++MiniXftConfig_c_buf_p;

			switch ( MiniXftConfig_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because MiniXftConfig_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					MiniXftConfigrestart( MiniXftConfigin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( MiniXftConfigwrap() )
						return EOF;

					if ( ! MiniXftConfig_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return MiniXftConfiginput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					MiniXftConfig_c_buf_p = MiniXftConfigtext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) MiniXftConfig_c_buf_p;	/* cast for 8-bit char's */
	*MiniXftConfig_c_buf_p = '\0';	/* preserve MiniXftConfigtext */
	MiniXftConfig_hold_char = *++MiniXftConfig_c_buf_p;

	MiniXftConfig_current_buffer->MiniXftConfig_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void MiniXftConfigrestart( FILE *input_file )
#else
void MiniXftConfigrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! MiniXftConfig_current_buffer )
		MiniXftConfig_current_buffer = MiniXftConfig_create_buffer( MiniXftConfigin, YY_BUF_SIZE );

	MiniXftConfig_init_buffer( MiniXftConfig_current_buffer, input_file );
	MiniXftConfig_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void MiniXftConfig_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void MiniXftConfig_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( MiniXftConfig_current_buffer == new_buffer )
		return;

	if ( MiniXftConfig_current_buffer )
		{
		/* Flush out information for old buffer. */
		*MiniXftConfig_c_buf_p = MiniXftConfig_hold_char;
		MiniXftConfig_current_buffer->MiniXftConfig_buf_pos = MiniXftConfig_c_buf_p;
		MiniXftConfig_current_buffer->MiniXftConfig_n_chars = MiniXftConfig_n_chars;
		}

	MiniXftConfig_current_buffer = new_buffer;
	MiniXftConfig_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (MiniXftConfigwrap()) processing, but the only time this flag
	 * is looked at is after MiniXftConfigwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	MiniXftConfig_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void MiniXftConfig_load_buffer_state( void )
#else
void MiniXftConfig_load_buffer_state()
#endif
	{
	MiniXftConfig_n_chars = MiniXftConfig_current_buffer->MiniXftConfig_n_chars;
	MiniXftConfigtext_ptr = MiniXftConfig_c_buf_p = MiniXftConfig_current_buffer->MiniXftConfig_buf_pos;
	MiniXftConfigin = MiniXftConfig_current_buffer->MiniXftConfig_input_file;
	MiniXftConfig_hold_char = *MiniXftConfig_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE MiniXftConfig_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE MiniXftConfig_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) MiniXftConfig_flex_alloc( sizeof( struct MiniXftConfig_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in MiniXftConfig_create_buffer()" );

	b->MiniXftConfig_buf_size = size;

	/* MiniXftConfig_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->MiniXftConfig_ch_buf = (char *) MiniXftConfig_flex_alloc( b->MiniXftConfig_buf_size + 2 );
	if ( ! b->MiniXftConfig_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in MiniXftConfig_create_buffer()" );

	b->MiniXftConfig_is_our_buffer = 1;

	MiniXftConfig_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void MiniXftConfig_delete_buffer( YY_BUFFER_STATE b )
#else
void MiniXftConfig_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == MiniXftConfig_current_buffer )
		MiniXftConfig_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->MiniXftConfig_is_our_buffer )
		MiniXftConfig_flex_free( (void *) b->MiniXftConfig_ch_buf );

	MiniXftConfig_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void MiniXftConfig_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void MiniXftConfig_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	MiniXftConfig_flush_buffer( b );

	b->MiniXftConfig_input_file = file;
	b->MiniXftConfig_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->MiniXftConfig_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->MiniXftConfig_is_interactive = 0;
#else
	b->MiniXftConfig_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void MiniXftConfig_flush_buffer( YY_BUFFER_STATE b )
#else
void MiniXftConfig_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->MiniXftConfig_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->MiniXftConfig_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->MiniXftConfig_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->MiniXftConfig_buf_pos = &b->MiniXftConfig_ch_buf[0];

	b->MiniXftConfig_at_bol = 1;
	b->MiniXftConfig_buffer_status = YY_BUFFER_NEW;

	if ( b == MiniXftConfig_current_buffer )
		MiniXftConfig_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE MiniXftConfig_scan_buffer( char *base, MiniXftConfig_size_t size )
#else
YY_BUFFER_STATE MiniXftConfig_scan_buffer( base, size )
char *base;
MiniXftConfig_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) MiniXftConfig_flex_alloc( sizeof( struct MiniXftConfig_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in MiniXftConfig_scan_buffer()" );

	b->MiniXftConfig_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->MiniXftConfig_buf_pos = b->MiniXftConfig_ch_buf = base;
	b->MiniXftConfig_is_our_buffer = 0;
	b->MiniXftConfig_input_file = 0;
	b->MiniXftConfig_n_chars = b->MiniXftConfig_buf_size;
	b->MiniXftConfig_is_interactive = 0;
	b->MiniXftConfig_at_bol = 1;
	b->MiniXftConfig_fill_buffer = 0;
	b->MiniXftConfig_buffer_status = YY_BUFFER_NEW;

	MiniXftConfig_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE MiniXftConfig_scan_string( MiniXftConfigconst char *MiniXftConfig_str )
#else
YY_BUFFER_STATE MiniXftConfig_scan_string( MiniXftConfig_str )
MiniXftConfigconst char *MiniXftConfig_str;
#endif
	{
	int len;
	for ( len = 0; MiniXftConfig_str[len]; ++len )
		;

	return MiniXftConfig_scan_bytes( MiniXftConfig_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE MiniXftConfig_scan_bytes( MiniXftConfigconst char *bytes, int len )
#else
YY_BUFFER_STATE MiniXftConfig_scan_bytes( bytes, len )
MiniXftConfigconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	MiniXftConfig_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) MiniXftConfig_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in MiniXftConfig_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = MiniXftConfig_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in MiniXftConfig_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->MiniXftConfig_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void MiniXftConfig_push_state( int new_state )
#else
static void MiniXftConfig_push_state( new_state )
int new_state;
#endif
	{
	if ( MiniXftConfig_start_stack_ptr >= MiniXftConfig_start_stack_depth )
		{
		MiniXftConfig_size_t new_size;

		MiniXftConfig_start_stack_depth += YY_START_STACK_INCR;
		new_size = MiniXftConfig_start_stack_depth * sizeof( int );

		if ( ! MiniXftConfig_start_stack )
			MiniXftConfig_start_stack = (int *) MiniXftConfig_flex_alloc( new_size );

		else
			MiniXftConfig_start_stack = (int *) MiniXftConfig_flex_realloc(
					(void *) MiniXftConfig_start_stack, new_size );

		if ( ! MiniXftConfig_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	MiniXftConfig_start_stack[MiniXftConfig_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void MiniXftConfig_pop_state()
	{
	if ( --MiniXftConfig_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(MiniXftConfig_start_stack[MiniXftConfig_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int MiniXftConfig_top_state()
	{
	return MiniXftConfig_start_stack[MiniXftConfig_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void MiniXftConfig_fatal_error( MiniXftConfigconst char msg[] )
#else
static void MiniXftConfig_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine MiniXftConfigless() so it works in section 3 code. */

#undef MiniXftConfigless
#define MiniXftConfigless(n) \
	do \
		{ \
		/* Undo effects of setting up MiniXftConfigtext. */ \
		MiniXftConfigtext[MiniXftConfigleng] = MiniXftConfig_hold_char; \
		MiniXftConfig_c_buf_p = MiniXftConfigtext + n; \
		MiniXftConfig_hold_char = *MiniXftConfig_c_buf_p; \
		*MiniXftConfig_c_buf_p = '\0'; \
		MiniXftConfigleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef MiniXftConfigtext_ptr
#ifdef YY_USE_PROTOS
static void MiniXftConfig_flex_strncpy( char *s1, MiniXftConfigconst char *s2, int n )
#else
static void MiniXftConfig_flex_strncpy( s1, s2, n )
char *s1;
MiniXftConfigconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int MiniXftConfig_flex_strlen( MiniXftConfigconst char *s )
#else
static int MiniXftConfig_flex_strlen( s )
MiniXftConfigconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *MiniXftConfig_flex_alloc( MiniXftConfig_size_t size )
#else
static void *MiniXftConfig_flex_alloc( size )
MiniXftConfig_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *MiniXftConfig_flex_realloc( void *ptr, MiniXftConfig_size_t size )
#else
static void *MiniXftConfig_flex_realloc( ptr, size )
void *ptr;
MiniXftConfig_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void MiniXftConfig_flex_free( void *ptr )
#else
static void MiniXftConfig_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	MiniXftConfiglex();
	return 0;
	}
#endif
#line 154 "minixftlex.l"

static void
_MiniXftConfigSkipComment (void)
{
    int	c;

    c = input();
    for (;;) {
	while (c != EOF && c != '*')
	    c = input();
	if (c == EOF)
	    return;
	c = input();
	if (c == EOF || c == '/')
	    return;
    }
}

static void
_MiniXftConfigSkipLine (void)
{
    int	    c;

    do {
	c = input();
    } while (c != EOF && c != '\n');
    if (c == '\n') unput('\n');
}

Bool
MiniXftConfigLexFile(char *s)
{
    FILE    *f;
    
    f = fopen (s, "r");
    if (f == 0) 
    {
	fprintf (stderr, "cannot open file \"%s\"\n", s);
	return False;
    }
    ++MiniXftConfigFiledeep;
    MiniXftConfigInput = f;
    MiniXftConfigFile = s;
    return True;
}
	
Bool
MiniXftConfigPushInput (char *s, Bool complain)
{
    FILE	*f;
    char	*t;
    char	*h;

    if (MiniXftConfigInpt == MiniXftConfigInStack) 
    {
	(void) fprintf (stderr, "files nested too deeply\n");
	return False;
    }
    t = s;
    if (*s == '~')
    {
	h = getenv ("HOME");
	if (h)
	{
	    t = (char *) malloc (strlen (h) + strlen (s));
	    if (t)
	    {
		strcpy (t, h);
		strcat (t, s+1);
	    }
	    else
		t = s;
	}
    }
    f = fopen (t, "r");
    if (t != s)
	free (t);
    if (f == 0) 
    {
	if (complain)
	    (void) fprintf (stderr, "cannot open file %s\n", s);
	return False;
    }
    ++MiniXftConfigFiledeep;
    *--MiniXftConfigInpt = MiniXftConfigInput;
    *--MiniXftConfigLinenopt = MiniXftConfigLineno;
    *--MiniXftConfigFileNamePt = MiniXftConfigFile;
    MiniXftConfigInput = f;
    MiniXftConfigLineno = 1;
    MiniXftConfigFile = _MiniXftSaveString (s);
    return True;
}

static int
_MiniXftConfigPopInput (void)
{
    int	    c;

    for (;;)
    {
	c = getc (MiniXftConfigInput);
	if (c >= 0)
	    return c;
	fclose (MiniXftConfigInput);
	MiniXftConfigInput = 0;
	if (MiniXftConfigInpt == MiniXftConfigInStack + XFT_CONFIG_IN_DEEP)
	    return EOF;
	MiniXftConfigInput = *MiniXftConfigInpt++;
	MiniXftConfigLineno = *MiniXftConfigLinenopt++;
	free (MiniXftConfigFile);
	MiniXftConfigFile = *MiniXftConfigFileNamePt++;
	--MiniXftConfigFiledeep;
    }
}

void
MiniXftConfigLexDone (void)
{
#ifdef FLEX_SCANNER
    MiniXftConfig_delete_buffer (MiniXftConfig_current_buffer);
#endif
}
