include:
  - project: 'Infrastructure/freedesktop-ci-templates'
    ref: '707b49ef'
    file:
      - 'templates/fedora.yml'
      - 'templates/debian.yml'
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      dist-job-name: "linux-fedora"
      tarball-artifact-path: "_build/meson-dist/$CI_PROJECT_NAME-$CI_COMMIT_TAG.tar.xz"

stages:
  - prepare
  - build
  - analysis
  - docs
  - deploy
  - release

# Common variables
variables:
  FDO_UPSTREAM_REPO: GNOME/pango
  COMMON_MESON_FLAGS: ""
  MESON_TEST_TIMEOUT_MULTIPLIER: 2

workflow:
  rules:
    # run merge request pipelines
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # do not run branch pipelines if corresponding merge requests exist...
    # (this avoids duplicate pipelines)
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    # ...but otherwise run branch pipelines
    - if: $CI_COMMIT_BRANCH
    # run tag pipelines
    - if: $CI_COMMIT_TAG

default:
  retry:
    max: 2
    when:
      - 'runner_system_failure'
      - 'stuck_or_timeout_failure'
      - 'scheduler_failure'
      - 'api_failure'
  interruptible: true

.container.fedora:
  variables:
    BASE_TAG: '2026-02-17.0'
    FDO_DISTRIBUTION_VERSION: 44
    FDO_DISTRIBUTION_TAG: "x86_64-${BASE_TAG}"
    FDO_DISTRIBUTION_PACKAGES:
      ccache
      clang
      clang-analyzer
      clang-tools-extra
      cmake
      compiler-rt
      dbus-daemon
      dejavu-sans-mono-fonts
      diffutils
      git
      glibc-langpack-en
      graphviz
      libasan
      libubsan
      meson
      mingw64-binutils
      mingw64-cairo
      mingw64-filesystem
      mingw64-gcc
      mingw64-gdk-pixbuf
      mingw64-glib2
      python-devel
      python3-jinja2
      python3-markdown
      python3-markupsafe
      python3-pip
      python3-pygments
      python3-typogrify
    FDO_DISTRIBUTION_EXEC: |
      dnf builddep -y gtk4 &&
      meson subprojects download || exit 137 &&
      meson subprojects update --reset || exit 137 &&
      mkdir /subprojects && find subprojects -mindepth 1 -maxdepth 1 -type d -exec mv {} /subprojects \;

.distribution.fedora:
  extends:
    - .fdo.distribution-image@fedora
    - .container.fedora

container:fedora:
  extends:
    - .container.fedora
    - .fdo.container-build@fedora@x86_64
  # DNS issues can cause this to fail
  retry:
    max: 2
    exit_codes: 137
  stage: prepare

linux-fedora:
  extends:
    - .distribution.fedora
  stage: build
  needs: ["container:fedora"]
  variables:
    EXTRA_MESON_FLAGS: "--buildtype=debug --default-library=both"
  script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - meson setup ${COMMON_MESON_FLAGS} ${EXTRA_MESON_FLAGS} _build
    - meson compile -C _build
    - .gitlab-ci/run-tests.sh _build
    - meson dist -C _build --include-subprojects --no-tests
  artifacts:
    name: "${env:CI_JOB_NAME}-${env:CI_COMMIT_REF_NAME}"
    when: always
    reports:
      junit:
        - "${CI_PROJECT_DIR}/_build/meson-logs/testlog.junit.xml"
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs"
      - "${CI_PROJECT_DIR}/_build/meson-dist/*.tar.xz"
      - "${CI_PROJECT_DIR}/_build/hello.png"
      - "${CI_PROJECT_DIR}/_build/fontlist.txt"

asan-build:
  extends:
    - .distribution.fedora
  tags: [ asan ]
  stage: analysis
  needs: []
  script:
    - CC=clang meson setup --buildtype=debugoptimized -Db_sanitize=address -Db_lundef=false -Dintrospection=disabled _build
    - meson compile -C _build
    - .gitlab-ci/run-tests.sh _build
  artifacts:
    name: "${env:CI_JOB_NAME}-${env:CI_COMMIT_REF_NAME}"
    when: always
    reports:
      junit:
        - "${CI_PROJECT_DIR}/_build/meson-logs/testlog.junit.xml"
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs"
      - "${CI_PROJECT_DIR}/_build/hello.png"
      - "${CI_PROJECT_DIR}/_build/fontlist.txt"

msys2-mingw64:
  stage: build
  needs: []
  tags:
    - win32-ps
  variables:
    MSYSTEM: "MINGW64"
    CHERE_INVOKING: "yes"
  script:
    - C:\msys64\usr\bin\pacman --noconfirm -Syyuu
    - C:\msys64\usr\bin\bash -lc "bash -x ./.gitlab-ci/test-msys2.sh"
    - C:\msys64\usr\bin\bash -lc "bash -x ./.gitlab-ci/render-msys2.sh"
    - C:\msys64\usr\bin\bash -lc "bash -x ./.gitlab-ci/list-msys2.sh"
  artifacts:
    name: "${env:CI_JOB_NAME}-${env:CI_COMMIT_REF_NAME}"
    when: always
    reports:
      junit:
        - "${CI_PROJECT_DIR}/_build/meson-logs/testlog.junit.xml"
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs"
      - "${CI_PROJECT_DIR}/_build/hello.png"
      - "${CI_PROJECT_DIR}/_build/fontlist.txt"

vs2019-x64:
  # TODO: Uncomment this when ready to merge.
  # rules:
  #   - if: $CI_PROJECT_NAMESPACE == "GNOME"
  stage: build
  tags:
    - win32-ps
  needs: []
  script:
    - .gitlab-ci/test-msvc.bat
  artifacts:
    name: "${env:CI_JOB_NAME}-${env:CI_COMMIT_REF_NAME}"
    when: always
    reports:
      junit:
        - "${CI_PROJECT_DIR}/_build/meson-logs/testlog.junit.xml"
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs"

macos:
  only:
    - branches@GNOME/pango
    - branches@dehesselle/pango
  stage: build
  tags:
    - macos
    - arm64
  needs: []
  variables:
    # ragel     -Wno-unused-const-variable, -Wno-overloaded-virtual
    # pcre2     -Wno-overlength-strings
    # glib      -Wno-deprecated-declarations, -Wno-literal-conversion
    # fribidi   -Wno-deprecated-non-prototype, -Wno-enum-conversion
    # libpng    -Wno-unused-but-set-variable
    # pixman    -Wno-unknown-attributes
    # cairo     -Wno-switch-enum, -Wno-deprecated-declarations, -Wno-unused-const-variable
    CFLAGS: "-Wno-overlength-strings -Wno-deprecated-non-prototype -Wno-enum-conversion -Wno-unused-but-set-variable -Wno-unknown-attributes -Wno-switch-enum -Wno-deprecated-declarations -Wno-unused-const-variable -Wno-literal-conversion"
    CXXFLAGS: "-Wno-overloaded-virtual -Wno-unused-const-variable"
    OBJCFLAGS: -Wno-deprecated-declarations
    CCACHE_DIR: /Users/Shared/work/ccache
    CCACHE_VER: "4.9.1"
    CCACHE_URL: https://github.com/ccache/ccache/releases/download/v$CCACHE_VER/ccache-$CCACHE_VER-darwin.tar.gz
    EXTRA_MESON_FLAGS: "-Dintrospection=disabled -Dpixman:tests=disabled -Dharfbuzz:ragel_subproject=true"
    PIP_CACHE_DIR: /Users/Shared/work/cache
    PIPENV_CACHE_DIR: $PIP_CACHE_DIR
    PYTHONPYCACHEPREFIX: $PIP_CACHE_DIR
    SDKROOT: /opt/sdks/MacOSX11.3.sdk
  before_script:
    - python3 -m venv .venv
    - curl -L $CCACHE_URL | tar -C .venv/bin -xz --strip-components=1 ccache-$CCACHE_VER-darwin/ccache
    - source .venv/bin/activate
    - pip3 install meson==1.8.0 ninja==1.11.1.1 packaging==23.2
    # Disable font-scale test as it SIGTRAPs. (The test code is skipped over by
    # inserting "return;" as first statement into the relevant function.)
    - |
      LINE_NO=$(grep -n "test_font_scale (void)" tests/test-font.c | awk -F ':' '{ print $1 }')
      sed -i '' ''$((LINE_NO+2))'i\
      return;' tests/test-font.c
  script:
    - meson setup ${COMMON_MESON_FLAGS} ${EXTRA_MESON_FLAGS} _build
    - meson compile -C _build
    - .gitlab-ci/run-tests.sh _build
  artifacts:
    name: "${env:CI_JOB_NAME}-${env:CI_COMMIT_REF_NAME}"
    when: always
    reports:
      junit:
        - "${CI_PROJECT_DIR}/_build/meson-logs/testlog.junit.xml"
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs"
      - "${CI_PROJECT_DIR}/_build/hello.png"
      - "${CI_PROJECT_DIR}/_build/fontlist.txt"

reference:
  extends:
    - .distribution.fedora
  stage: docs
  needs: []
  variables:
    EXTRA_MESON_FLAGS: ""
  script:
    - meson ${COMMON_MESON_FLAGS} ${EXTRA_MESON_FLAGS} -Ddocumentation=true _build
    - ninja -C _build
    - mkdir -p _reference/
    - mv _build/docs/Pango/ _reference/
    - mv _build/docs/PangoCairo/ _reference/
    - mv _build/docs/PangoFc/ _reference/
    - mv _build/docs/PangoFT2/ _reference/
    - mv _build/docs/PangoOT/ _reference/
    - mv _build/docs/PangoXft/ _reference/
  artifacts:
    paths:
      - _reference

pages:
  stage: deploy
  needs: ['reference']
  script:
    - mv _reference/ public/
  artifacts:
    paths:
      - public
  only:
    - main
