/* Autogenerated by configure. Do not edit */

#include "modules.h"

extern void         _pango_arabic_lang_script_engine_list (PangoEngineInfo **engines, int *n_engines);
extern void         _pango_arabic_lang_script_engine_init (GTypeModule *module);
extern void         _pango_arabic_lang_script_engine_exit (void);
extern PangoEngine *_pango_arabic_lang_script_engine_create (const char *id);

extern void         _pango_basic_fc_script_engine_list (PangoEngineInfo **engines, int *n_engines);
extern void         _pango_basic_fc_script_engine_init (GTypeModule *module);
extern void         _pango_basic_fc_script_engine_exit (void);
extern PangoEngine *_pango_basic_fc_script_engine_create (const char *id);

extern void         _pango_basic_win32_script_engine_list (PangoEngineInfo **engines, int *n_engines);
extern void         _pango_basic_win32_script_engine_init (GTypeModule *module);
extern void         _pango_basic_win32_script_engine_exit (void);
extern PangoEngine *_pango_basic_win32_script_engine_create (const char *id);

extern void         _pango_basic_coretext_script_engine_list (PangoEngineInfo **engines, int *n_engines);
extern void         _pango_basic_coretext_script_engine_init (GTypeModule *module);
extern void         _pango_basic_coretext_script_engine_exit (void);
extern PangoEngine *_pango_basic_coretext_script_engine_create (const char *id);

extern void         _pango_indic_lang_script_engine_list (PangoEngineInfo **engines, int *n_engines);
extern void         _pango_indic_lang_script_engine_init (GTypeModule *module);
extern void         _pango_indic_lang_script_engine_exit (void);
extern PangoEngine *_pango_indic_lang_script_engine_create (const char *id);

