/* Pango
 * pango-script.h: Script tag handling
 *
 * Copyright (C) 2002 Red Hat Software
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

#ifndef __PANGO_SCRIPT_H__
#define __PANGO_SCRIPT_H__

#include <glib.h>

G_BEGIN_DECLS

/**
 * PangoScriptIter:
 *
 * A #PangoScriptIter is used to iterate through a string
 * and identify ranges in different scripts.
 **/
typedef struct _PangoScriptIter PangoScriptIter;

/**
 * PangoScript:
 * @PANGO_SCRIPT_INVALID_CODE: a value never returned from pango_script_for_unichar()
 * @PANGO_SCRIPT_COMMON: a character used by multiple different scripts
 * @PANGO_SCRIPT_INHERITED: a mark glyph that takes its script from the
 * base glyph to which it is attached
 * @PANGO_SCRIPT_ARABIC: 	Arabic
 * @PANGO_SCRIPT_ARMENIAN: Armenian
 * @PANGO_SCRIPT_BENGALI: 	Bengali
 * @PANGO_SCRIPT_BOPOMOFO: Bopomofo
 * @PANGO_SCRIPT_CHEROKEE: 	Cherokee
 * @PANGO_SCRIPT_COPTIC: 	Coptic
 * @PANGO_SCRIPT_CYRILLIC: 	Cyrillic
 * @PANGO_SCRIPT_DESERET: 	Deseret
 * @PANGO_SCRIPT_DEVANAGARI: 	Devanagari
 * @PANGO_SCRIPT_ETHIOPIC: 	Ethiopic
 * @PANGO_SCRIPT_GEORGIAN: 	Georgian
 * @PANGO_SCRIPT_GOTHIC: 	Gothic
 * @PANGO_SCRIPT_GREEK: 	Greek
 * @PANGO_SCRIPT_GUJARATI: 	Gujarati
 * @PANGO_SCRIPT_GURMUKHI: 	Gurmukhi
 * @PANGO_SCRIPT_HAN: 	Han
 * @PANGO_SCRIPT_HANGUL: 	Hangul
 * @PANGO_SCRIPT_HEBREW: 	Hebrew
 * @PANGO_SCRIPT_HIRAGANA: 	Hiragana
 * @PANGO_SCRIPT_KANNADA: 	Kannada
 * @PANGO_SCRIPT_KATAKANA: 	Katakana
 * @PANGO_SCRIPT_KHMER: 	Khmer
 * @PANGO_SCRIPT_LAO: 	Lao
 * @PANGO_SCRIPT_LATIN: 	Latin
 * @PANGO_SCRIPT_MALAYALAM: 	Malayalam
 * @PANGO_SCRIPT_MONGOLIAN: 	Mongolian
 * @PANGO_SCRIPT_MYANMAR: 	Myanmar
 * @PANGO_SCRIPT_OGHAM: 	Ogham
 * @PANGO_SCRIPT_OLD_ITALIC: 	Old Italic
 * @PANGO_SCRIPT_ORIYA: 	Oriya
 * @PANGO_SCRIPT_RUNIC: 	Runic
 * @PANGO_SCRIPT_SINHALA: 	Sinhala
 * @PANGO_SCRIPT_SYRIAC: 	Syriac
 * @PANGO_SCRIPT_TAMIL: 	Tamil
 * @PANGO_SCRIPT_TELUGU: 	Telugu
 * @PANGO_SCRIPT_THAANA: 	Thaana
 * @PANGO_SCRIPT_THAI: 	Thai
 * @PANGO_SCRIPT_TIBETAN: 	Tibetan
 * @PANGO_SCRIPT_CANADIAN_ABORIGINAL: 	Canadian Aboriginal
 * @PANGO_SCRIPT_YI: 	Yi
 * @PANGO_SCRIPT_TAGALOG: 	Tagalog
 * @PANGO_SCRIPT_HANUNOO: 	Hanunoo
 * @PANGO_SCRIPT_BUHID: 	Buhid
 * @PANGO_SCRIPT_TAGBANWA: 	Tagbanwa
 * @PANGO_SCRIPT_BRAILLE: 	Braille
 * @PANGO_SCRIPT_CYPRIOT: 	Cypriot
 * @PANGO_SCRIPT_LIMBU: 	Limbu
 * @PANGO_SCRIPT_OSMANYA: 	Osmanya
 * @PANGO_SCRIPT_SHAVIAN: 	Shavian
 * @PANGO_SCRIPT_LINEAR_B: 	Linear B
 * @PANGO_SCRIPT_TAI_LE: 	Tai Le
 * @PANGO_SCRIPT_UGARITIC: 	Ugaritic
 * @PANGO_SCRIPT_NEW_TAI_LUE: 	New Tai Lue. Since 1.10
 * @PANGO_SCRIPT_BUGINESE: 	Buginese. Since 1.10
 * @PANGO_SCRIPT_GLAGOLITIC: 	Glagolitic. Since 1.10
 * @PANGO_SCRIPT_TIFINAGH: 	Tifinagh. Since 1.10
 * @PANGO_SCRIPT_SYLOTI_NAGRI: 	Syloti Nagri. Since 1.10
 * @PANGO_SCRIPT_OLD_PERSIAN: 	Old Persian. Since 1.10
 * @PANGO_SCRIPT_KHAROSHTHI: 	Kharoshthi. Since 1.10
 * @PANGO_SCRIPT_UNKNOWN: 		an unassigned code point. Since 1.14
 * @PANGO_SCRIPT_BALINESE: 		Balinese. Since 1.14
 * @PANGO_SCRIPT_CUNEIFORM: 	Cuneiform. Since 1.14
 * @PANGO_SCRIPT_PHOENICIAN: 	Phoenician. Since 1.14
 * @PANGO_SCRIPT_PHAGS_PA: 		Phags-pa. Since 1.14
 * @PANGO_SCRIPT_NKO: 		N'Ko. Since 1.14
 * @PANGO_SCRIPT_KAYAH_LI:   Kayah Li. Since 1.20.1
 * @PANGO_SCRIPT_LEPCHA:     Lepcha. Since 1.20.1
 * @PANGO_SCRIPT_REJANG:     Rejang. Since 1.20.1
 * @PANGO_SCRIPT_SUNDANESE:  Sundanese. Since 1.20.1
 * @PANGO_SCRIPT_SAURASHTRA: Saurashtra. Since 1.20.1
 * @PANGO_SCRIPT_CHAM:       Cham. Since 1.20.1
 * @PANGO_SCRIPT_OL_CHIKI:   Ol Chiki. Since 1.20.1
 * @PANGO_SCRIPT_VAI:        Vai. Since 1.20.1
 * @PANGO_SCRIPT_CARIAN:     Carian. Since 1.20.1
 * @PANGO_SCRIPT_LYCIAN:     Lycian. Since 1.20.1
 * @PANGO_SCRIPT_LYDIAN:     Lydian. Since 1.20.1
 * @PANGO_SCRIPT_BATAK:      Batak. Since 1.32
 * @PANGO_SCRIPT_BRAHMI:     Brahmi. Since 1.32
 * @PANGO_SCRIPT_MANDAIC:    Mandaic. Since 1.32
 * @PANGO_SCRIPT_CHAKMA:               Chakma. Since: 1.32
 * @PANGO_SCRIPT_MEROITIC_CURSIVE:     Meroitic Cursive. Since: 1.32
 * @PANGO_SCRIPT_MEROITIC_HIEROGLYPHS: Meroitic Hieroglyphs. Since: 1.32
 * @PANGO_SCRIPT_MIAO:                 Miao. Since: 1.32
 * @PANGO_SCRIPT_SHARADA:              Sharada. Since: 1.32
 * @PANGO_SCRIPT_SORA_SOMPENG:         Sora Sompeng. Since: 1.32
 * @PANGO_SCRIPT_TAKRI:                Takri. Since: 1.32
 * @PANGO_SCRIPT_BASSA_VAH:            Bassa. Since: 1.40
 * @PANGO_SCRIPT_CAUCASIAN_ALBANIAN:   Caucasian Albanian. Since: 1.40
 * @PANGO_SCRIPT_DUPLOYAN:             Duployan. Since: 1.40
 * @PANGO_SCRIPT_ELBASAN:              Elbasan. Since: 1.40
 * @PANGO_SCRIPT_GRANTHA:              Grantha. Since: 1.40
 * @PANGO_SCRIPT_KHOJKI:               Kjohki. Since: 1.40
 * @PANGO_SCRIPT_KHUDAWADI:            Khudawadi, Sindhi. Since: 1.40
 * @PANGO_SCRIPT_LINEAR_A:             Linear A. Since: 1.40
 * @PANGO_SCRIPT_MAHAJANI:             Mahajani. Since: 1.40
 * @PANGO_SCRIPT_MANICHAEAN:           Manichaean. Since: 1.40
 * @PANGO_SCRIPT_MENDE_KIKAKUI:        Mende Kikakui. Since: 1.40
 * @PANGO_SCRIPT_MODI:                 Modi. Since: 1.40
 * @PANGO_SCRIPT_MRO:                  Mro. Since: 1.40
 * @PANGO_SCRIPT_NABATAEAN:            Nabataean. Since: 1.40
 * @PANGO_SCRIPT_OLD_NORTH_ARABIAN:    Old North Arabian. Since: 1.40
 * @PANGO_SCRIPT_OLD_PERMIC:           Old Permic. Since: 1.40
 * @PANGO_SCRIPT_PAHAWH_HMONG:         Pahawh Hmong. Since: 1.40
 * @PANGO_SCRIPT_PALMYRENE:            Palmyrene. Since: 1.40
 * @PANGO_SCRIPT_PAU_CIN_HAU:          Pau Cin Hau. Since: 1.40
 * @PANGO_SCRIPT_PSALTER_PAHLAVI:      Psalter Pahlavi. Since: 1.40
 * @PANGO_SCRIPT_SIDDHAM:              Siddham. Since: 1.40
 * @PANGO_SCRIPT_TIRHUTA:              Tirhuta. Since: 1.40
 * @PANGO_SCRIPT_WARANG_CITI:          Warang Citi. Since: 1.40
 * @PANGO_SCRIPT_AHOM:                 Ahom. Since: 1.40
 * @PANGO_SCRIPT_ANATOLIAN_HIEROGLYPHS: Anatolian Hieroglyphs. Since: 1.40
 * @PANGO_SCRIPT_HATRAN:               Hatran. Since: 1.40
 * @PANGO_SCRIPT_MULTANI:              Multani. Since: 1.40
 * @PANGO_SCRIPT_OLD_HUNGARIAN:        Old Hungarian. Since: 1.40
 * @PANGO_SCRIPT_SIGNWRITING:          Signwriting. Since: 1.40
 *
 * The #PangoScript enumeration identifes different writing
 * systems. The values correspond to the names as defined in the
 * Unicode standard.
 * Note that new types may be added in the future. Applications should be ready
 * to handle unknown values.  This enumeration is interchangeable with
 * #GUnicodeScript.  See <ulink
 * url="http://www.unicode.org/reports/tr24/">Unicode Standard Annex
 * #24: Script names</ulink>.
 * 
 * Applications should use the GUnicodeScript enumeration directly.
 * PangoScript is deprecated. The current PANGO_SCRIPT_ values are
 * preserved for compatibility, but new values will only be added
 * in the G_UNICODE_SCRIPT_ namespace.
 */
typedef GUnicodeScript PangoScript;

#define PANGO_SCRIPT_INVALID_CODE G_UNICODE_SCRIPT_INVALID_CODE
#define PANGO_SCRIPT_COMMON G_UNICODE_SCRIPT_COMMON
#define PANGO_SCRIPT_INHERITED G_UNICODE_SCRIPT_INHERITED
#define PANGO_SCRIPT_ARABIC G_UNICODE_SCRIPT_ARABIC
#define PANGO_SCRIPT_ARMENIAN G_UNICODE_SCRIPT_ARMENIAN
#define PANGO_SCRIPT_BENGALI G_UNICODE_SCRIPT_BENGALI
#define PANGO_SCRIPT_BOPOMOFO G_UNICODE_SCRIPT_BOPOMOFO
#define PANGO_SCRIPT_CHEROKEE G_UNICODE_SCRIPT_CHEROKEE
#define PANGO_SCRIPT_COPTIC G_UNICODE_SCRIPT_COPTIC
#define PANGO_SCRIPT_CYRILLIC G_UNICODE_SCRIPT_CYRILLIC
#define PANGO_SCRIPT_DESERET G_UNICODE_SCRIPT_DESERET
#define PANGO_SCRIPT_DEVANAGARI G_UNICODE_SCRIPT_DEVANAGARI
#define PANGO_SCRIPT_ETHIOPIC G_UNICODE_SCRIPT_ETHIOPIC
#define PANGO_SCRIPT_GEORGIAN G_UNICODE_SCRIPT_GEORGIAN
#define PANGO_SCRIPT_GOTHIC G_UNICODE_SCRIPT_GOTHIC
#define PANGO_SCRIPT_GREEK G_UNICODE_SCRIPT_GREEK
#define PANGO_SCRIPT_GUJARATI G_UNICODE_SCRIPT_GUJARATI
#define PANGO_SCRIPT_GURMUKHI G_UNICODE_SCRIPT_GURMUKHI
#define PANGO_SCRIPT_HAN G_UNICODE_SCRIPT_HAN
#define PANGO_SCRIPT_HANGUL G_UNICODE_SCRIPT_HANGUL
#define PANGO_SCRIPT_HEBREW G_UNICODE_SCRIPT_HEBREW
#define PANGO_SCRIPT_HIRAGANA G_UNICODE_SCRIPT_HIRAGANA
#define PANGO_SCRIPT_KANNADA G_UNICODE_SCRIPT_KANNADA
#define PANGO_SCRIPT_KATAKANA G_UNICODE_SCRIPT_KATAKANA
#define PANGO_SCRIPT_KHMER G_UNICODE_SCRIPT_KHMER
#define PANGO_SCRIPT_LAO G_UNICODE_SCRIPT_LAO
#define PANGO_SCRIPT_LATIN G_UNICODE_SCRIPT_LATIN
#define PANGO_SCRIPT_MALAYALAM G_UNICODE_SCRIPT_MALAYALAM
#define PANGO_SCRIPT_MONGOLIAN G_UNICODE_SCRIPT_MONGOLIAN
#define PANGO_SCRIPT_MYANMAR G_UNICODE_SCRIPT_MYANMAR
#define PANGO_SCRIPT_OGHAM G_UNICODE_SCRIPT_OGHAM
#define PANGO_SCRIPT_OLD_ITALIC G_UNICODE_SCRIPT_OLD_ITALIC
#define PANGO_SCRIPT_ORIYA G_UNICODE_SCRIPT_ORIYA
#define PANGO_SCRIPT_RUNIC G_UNICODE_SCRIPT_RUNIC
#define PANGO_SCRIPT_SINHALA G_UNICODE_SCRIPT_SINHALA
#define PANGO_SCRIPT_SYRIAC G_UNICODE_SCRIPT_SYRIAC
#define PANGO_SCRIPT_TAMIL G_UNICODE_SCRIPT_TAMIL
#define PANGO_SCRIPT_TELUGU G_UNICODE_SCRIPT_TELUGU
#define PANGO_SCRIPT_THAANA G_UNICODE_SCRIPT_THAANA
#define PANGO_SCRIPT_THAI G_UNICODE_SCRIPT_THAI
#define PANGO_SCRIPT_TIBETAN G_UNICODE_SCRIPT_TIBETAN
#define PANGO_SCRIPT_CANADIAN_ABORIGINAL G_UNICODE_SCRIPT_CANADIAN_ABORIGINAL
#define PANGO_SCRIPT_YI G_UNICODE_SCRIPT_YI
#define PANGO_SCRIPT_TAGALOG G_UNICODE_SCRIPT_TAGALOG
#define PANGO_SCRIPT_HANUNOO G_UNICODE_SCRIPT_HANUNOO
#define PANGO_SCRIPT_BUHID G_UNICODE_SCRIPT_BUHID
#define PANGO_SCRIPT_TAGBANWA G_UNICODE_SCRIPT_TAGBANWA
#define PANGO_SCRIPT_BRAILLE G_UNICODE_SCRIPT_BRAILLE
#define PANGO_SCRIPT_CYPRIOT G_UNICODE_SCRIPT_CYPRIOT
#define PANGO_SCRIPT_LIMBU G_UNICODE_SCRIPT_LIMBU
#define PANGO_SCRIPT_OSMANYA G_UNICODE_SCRIPT_OSMANYA
#define PANGO_SCRIPT_SHAVIAN G_UNICODE_SCRIPT_SHAVIAN
#define PANGO_SCRIPT_LINEAR_B G_UNICODE_SCRIPT_LINEAR_B
#define PANGO_SCRIPT_TAI_LE G_UNICODE_SCRIPT_TAI_LE
#define PANGO_SCRIPT_UGARITIC G_UNICODE_SCRIPT_UGARITIC
#define PANGO_SCRIPT_NEW_TAI_LUE G_UNICODE_SCRIPT_NEW_TAI_LUE
#define PANGO_SCRIPT_BUGINESE G_UNICODE_SCRIPT_BUGINESE
#define PANGO_SCRIPT_GLAGOLITIC G_UNICODE_SCRIPT_GLAGOLITIC
#define PANGO_SCRIPT_TIFINAGH G_UNICODE_SCRIPT_TIFINAGH
#define PANGO_SCRIPT_SYLOTI_NAGRI G_UNICODE_SCRIPT_SYLOTI_NAGRI
#define PANGO_SCRIPT_OLD_PERSIAN G_UNICODE_SCRIPT_OLD_PERSIAN
#define PANGO_SCRIPT_KHAROSHTHI G_UNICODE_SCRIPT_KHAROSHTHI
#define PANGO_SCRIPT_UNKNOWN G_UNICODE_SCRIPT_UNKNOWN
#define PANGO_SCRIPT_BALINESE G_UNICODE_SCRIPT_BALINESE
#define PANGO_SCRIPT_CUNEIFORM G_UNICODE_SCRIPT_CUNEIFORM
#define PANGO_SCRIPT_PHOENICIAN G_UNICODE_SCRIPT_PHOENICIAN
#define PANGO_SCRIPT_PHAGS_PA G_UNICODE_SCRIPT_PHAGS_PA
#define PANGO_SCRIPT_NKO G_UNICODE_SCRIPT_NKO
#define PANGO_SCRIPT_KAYAH_LI G_UNICODE_SCRIPT_KAYAH_LI
#define PANGO_SCRIPT_LEPCHA G_UNICODE_SCRIPT_LEPCHA
#define PANGO_SCRIPT_REJANG G_UNICODE_SCRIPT_REJANG
#define PANGO_SCRIPT_SUNDANESE G_UNICODE_SCRIPT_SUNDANESE
#define PANGO_SCRIPT_SAURASHTRA G_UNICODE_SCRIPT_SAURASHTRA
#define PANGO_SCRIPT_CHAM G_UNICODE_SCRIPT_CHAM
#define PANGO_SCRIPT_OL_CHIKI G_UNICODE_SCRIPT_OL_CHIKI
#define PANGO_SCRIPT_VAI G_UNICODE_SCRIPT_VAI
#define PANGO_SCRIPT_CARIAN G_UNICODE_SCRIPT_CARIAN
#define PANGO_SCRIPT_LYCIAN G_UNICODE_SCRIPT_LYCIAN
#define PANGO_SCRIPT_LYDIAN G_UNICODE_SCRIPT_LYDIAN
#define PANGO_SCRIPT_BATAK G_UNICODE_SCRIPT_BATAK
#define PANGO_SCRIPT_BRAHMI G_UNICODE_SCRIPT_BRAHMI
#define PANGO_SCRIPT_MANDAIC G_UNICODE_SCRIPT_MANDAIC
#define PANGO_SCRIPT_CHAKMA G_UNICODE_SCRIPT_CHAKMA
#define PANGO_SCRIPT_MEROITIC_CURSIVE G_UNICODE_SCRIPT_MEROITIC_CURSIVE
#define PANGO_SCRIPT_MEROITIC_HIEROGLYPHS G_UNICODE_SCRIPT_MEROITIC_HIEROGLYPHS
#define PANGO_SCRIPT_MIAO G_UNICODE_SCRIPT_MIAO
#define PANGO_SCRIPT_SHARADA G_UNICODE_SCRIPT_SHARADA
#define PANGO_SCRIPT_SORA_SOMPENG G_UNICODE_SCRIPT_SORA_SOMPENG
#define PANGO_SCRIPT_TAKRI G_UNICODE_SCRIPT_TAKRI
#define PANGO_SCRIPT_BASSA_VAH G_UNICODE_SCRIPT_BASSA_VAH
#define PANGO_SCRIPT_CAUCASIAN_ALBANIAN G_UNICODE_SCRIPT_CAUCASIAN_ALBANIAN
#define PANGO_SCRIPT_DUPLOYAN G_UNICODE_SCRIPT_DUPLOYAN
#define PANGO_SCRIPT_ELBASAN G_UNICODE_SCRIPT_ELBASAN
#define PANGO_SCRIPT_GRANTHA G_UNICODE_SCRIPT_GRANTHA
#define PANGO_SCRIPT_KHOJKI G_UNICODE_SCRIPT_KHOJKI
#define PANGO_SCRIPT_KHUDAWADI G_UNICODE_SCRIPT_KHUDAWADI
#define PANGO_SCRIPT_LINEAR_A G_UNICODE_SCRIPT_LINEAR_A
#define PANGO_SCRIPT_MAHAJANI G_UNICODE_SCRIPT_MAHAJANI
#define PANGO_SCRIPT_MANICHAEAN G_UNICODE_SCRIPT_MANICHAEAN
#define PANGO_SCRIPT_MENDE_KIKAKUI G_UNICODE_SCRIPT_MENDE_KIKAKUI
#define PANGO_SCRIPT_MODI G_UNICODE_SCRIPT_MODI
#define PANGO_SCRIPT_MRO G_UNICODE_SCRIPT_MRO
#define PANGO_SCRIPT_NABATAEAN G_UNICODE_SCRIPT_NABATAEAN
#define PANGO_SCRIPT_OLD_NORTH_ARABIAN G_UNICODE_SCRIPT_OLD_NORTH_ARABIAN
#define PANGO_SCRIPT_OLD_PERMIC G_UNICODE_SCRIPT_OLD_PERMIC
#define PANGO_SCRIPT_PAHAWH_HMONG G_UNICODE_SCRIPT_PAHAWH_HMONG
#define PANGO_SCRIPT_PALMYRENE G_UNICODE_SCRIPT_PALMYRENE
#define PANGO_SCRIPT_PAU_CIN_HAU G_UNICODE_SCRIPT_PAU_CIN_HAU
#define PANGO_SCRIPT_PSALTER_PAHLAVI G_UNICODE_SCRIPT_PSALTER_PAHLAVI
#define PANGO_SCRIPT_SIDDHAM G_UNICODE_SCRIPT_SIDDHAM
#define PANGO_SCRIPT_TIRHUTA G_UNICODE_SCRIPT_TIRHUTA
#define PANGO_SCRIPT_WARANG_CITI G_UNICODE_SCRIPT_WARANG_CITI
#define PANGO_SCRIPT_AHOM G_UNICODE_SCRIPT_AHOM
#define PANGO_SCRIPT_ANATOLIAN_HIEROGLYPHS G_UNICODE_SCRIPT_ANATOLIAN_HIEROGLYPHS
#define PANGO_SCRIPT_HATRAN G_UNICODE_SCRIPT_HATRAN
#define PANGO_SCRIPT_MULTANI G_UNICODE_SCRIPT_MULTANI
#define PANGO_SCRIPT_OLD_HUNGARIAN G_UNICODE_SCRIPT_OLD_HUNGARIAN
#define PANGO_SCRIPT_SIGNWRITING G_UNICODE_SCRIPT_SIGNWRITING

#include <pango/pango-version-macros.h>

PANGO_AVAILABLE_IN_1_4
PangoScript pango_script_for_unichar         (gunichar             ch) G_GNUC_CONST;

PANGO_AVAILABLE_IN_1_4
PangoScriptIter *pango_script_iter_new       (const char          *text,
					      int                  length);
PANGO_AVAILABLE_IN_1_4
void             pango_script_iter_get_range (PangoScriptIter     *iter,
                                              const char         **start,
                                              const char         **end,
                                              PangoScript         *script);
PANGO_AVAILABLE_IN_1_4
gboolean         pango_script_iter_next      (PangoScriptIter     *iter);
PANGO_AVAILABLE_IN_1_4
void             pango_script_iter_free      (PangoScriptIter     *iter);

#include <pango/pango-language.h>

PANGO_AVAILABLE_IN_1_4
PangoLanguage *pango_script_get_sample_language (PangoScript    script) G_GNUC_PURE;

G_END_DECLS

#endif /* __PANGO_SCRIPT_H__ */
