PANGO_VER = 0.12

TOP = ../..

include $(TOP)/build/win32/make.mingw

OPTIMIZE = -g

INCLUDES = -I .. -I .
DEFINES = 
DEPCFLAGS = $(GTK_CFLAGS) $(GLIB_CFLAGS)

all : \
	../config.h \
	viewer-win32.exe

../config.h : ../config.h.win32
	cp $< $@

viewer-win32.exe : viewer-win32.o
	$(CC) -o $@ $< $(OPTIMIZE) -L ../pango -lpango-$(PANGO_VER) -lpangowin32-$(PANGO_VER) $(GTK_LIBS) $(GLIB_LIBS) -gdi32

