TOP = ../../..

include $(TOP)/build/win32/make.mingw

OPTIMIZE = -g -Wall

INCLUDES = -I ../.. -I ..
DEPCFLAGS = $(GLIB_CFLAGS)

all :						\
	../../config.h				\
	libmini-fribidi.a

MINI_FRIBIDI_OBJS =				\
	fribidi.o				\
	fribidi_get_type.o
../../config.h : ../../config.h.win32
	cp $< $@

libmini-fribidi.a : $(MINI_FRIBIDI_OBJS)
	-rm -f $@
	$(AR) rv $@ $(MINI_FRIBIDI_OBJS)
