[library]
namespace = "PangoOT"
version = "1.0"
browse_url = "https://gitlab.gnome.org/GNOME/pango/"
repository_url = "https://gitlab.gnome.org/GNOME/pango.git"
website_url = "https://www.pango.org"
authors = "Owen Taylor, Behdad Esfahbod"
logo_url = "pango-name.png"
license = "GPL-2.1-or-later"
description = "OpenType support for Pango"
dependencies = [ "Pango-1.0" ]

  [dependencies."Pango-1.0"]
  name = "Pango"
  description = "A library for layout out and rendering of text"
  docs_url = "https://developer.gnome.org/pango/stable"

[theme]
name = "basic"

[source-location]
base_url = "https://gitlab.gnome.org/GNOME/pango/-/blob/master/"

[extra]

content_images = [
  "pango-name.png"
]
